In [1]:
import numpy as np

HPP=[8,16,16]
AAA=[1,1,1]

first_matrix_2d=np.array([[8,16,16],[1,1,1]])
print(first_matrix_2d.shape)
print(first_matrix_2d.ndim)

first_matrix=first_matrix_2d

print('first_matrix')
for row in first_matrix:
    print(row)

(2, 3)
2
first_matrix
[ 8 16 16]
[1 1 1]


In [3]:
2023-4-0o207==[2,0,2]
2023-4-0o207==[2,0,7]

second_matrix_2d=np.array([[2,0,2],[2,0,7]])
print(second_matrix_2d.shape)
print(second_matrix_2d.ndim)

second_matrix=second_matrix_2d

print('second_matrix')
for row in second_matrix:
    print(row)

(2, 3)
2
second_matrix
[2 0 2]
[2 0 7]


In [4]:
print(first_matrix)
print(second_matrix)

[[ 8 16 16]
 [ 1  1  1]]
[[2 0 2]
 [2 0 7]]


In [5]:
array_first_matrix=np.array(first_matrix)
array_second_matrix=np.array(second_matrix)

third_matrix=(array_first_matrix+array_second_matrix)

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[10 16 18]
[3 1 8]


In [8]:
array_first_matrix=np.array(first_matrix)

fourth_matrix=(array_first_matrix*2)

print('fourth_matrix')
for row in fourth_matrix:
  print(row)


fourth_matrix
[16 32 32]
[2 2 2]


In [11]:
second_matrix=np.array(second_matrix)
second_matrix_T=second_matrix.T

fifth_matrix=(second_matrix.T)

print('fifth_matrix')
for row in fifth_matrix:
    print (row)

fifth_matrix
[2 2]
[0 0]
[2 7]


In [21]:
third_matrix=([[10, 16, 18],[3, 1, 8]])
third_matrix=np.array(third_matrix)
third_matrix_T=third_matrix.T

third_matrix=(third_matrix.T)

print('third_matrix')
for row in third_matrix:
  print(row)

third_matrix
[10  3]
[16  1]
[18  8]


In [24]:
array_third_matrix=np.array(third_matrix)
array_fifth_matrix=np.array(fifth_matrix)

sixth_matrix=(array_third_matrix*array_fifth_matrix)

print('sixth_matrix')
for row in sixth_matrix:
    print(row)

sixth_matrix
[20  6]
[0 0]
[36 56]


In [25]:
array_third_matrix=np.array(third_matrix)
sum_third_matrix=np.sum(third_matrix)

print(sum_third_matrix)

56


In [29]:
seventh_matrix=np.zeros((2,3))

print('seventh_matrix')
for row in seventh_matrix:
    print(row)

seventh_matrix
[0. 0. 0.]
[0. 0. 0.]
